# A sample Guardfile
# More info at https://github.com/guard/guard#readme

# Add files and commands to this file, like the example:
#   watch(%r{file/path}) { `command(s)` }
#
guard :shell do
  watch(%r{src/main/js}) { puts("Detected JS change"); `./gradlew compileJsPretty ; ./scripts/copy_for_guard.sh` }
  watch(%r{src/main/less}) { puts("Detected CSS change"); `./gradlew compileCss generateStyleGuide ; ./scripts/copy_for_guard.sh` }
end
